### ISSUE TITLE
Strings plugin

### ISSUE THREAD

**Issue by logikaljay** [logikaljay/mudjs#9]
Adds a group of procedures for string processing including:
- Lower
- Upper
- Left
- Right
- Mid
- Replace
- ConCat
- Len
- Trim
- LTrim
- RTrim
- WordCount
- CharCount
- PadLeft
- PadRight
- Word
- Char
- Strip
- IsEmpty

**Comment by logikaljay** [comment]
On second thought all of this is kinda core functionality for scripting and should be included in the core

**Comment by logikaljay** [comment]
Lower is done.
CharCount is irrelevant if Len exists

**Comment by ghost** [comment]
Upper is done

**Comment by logikaljay** [comment]
This has been implemented
